# Generated by Django 5.1.2 on 2024-10-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_consultor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExtratoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('plano', models.CharField(max_length=100)),
                ('parcela_numero', models.IntegerField()),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='nome',
            new_name='nome_plano',
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='tipo',
            new_name='tipo_plano',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='operadora',
        ),
        migrations.AlterField(
            model_name='plano',
            name='taxa_administrativa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ComissaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_numero', models.IntegerField()),
                ('porcentagem_comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=100, unique=True)),
                ('valor_plano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateField()),
                ('data_vigencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plano')),
            ],
        ),
        migrations.CreateModel(
            name='ControleRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_numero', models.IntegerField()),
                ('data_parcela', models.DateField()),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmacao_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Aguardando', 'Aguardando'), ('Inadimplente', 'Inadimplente')], default='Aguardando', max_length=20)),
                ('codigo_extrato', models.CharField(blank=True, max_length=100, null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venda')),
            ],
        ),
    ]
