# Generated by Django 5.1.2 on 2024-10-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente_consultor_extratoplataforma_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comissaoplano',
            unique_together={('plano', 'parcela_numero')},
        ),
    ]
